"""add_safe_mode_and_manual_card_visibility

Revision ID: 2cf59a786504
Revises: 5f9663eadacb
Create Date: 2026-07-08 04:18:18.583369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf59a786504'
down_revision: Union[str, None] = '5f9663eadacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('manual_card_visibility', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('safe_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'safe_mode')
    op.drop_column('settings', 'manual_card_visibility')
    # ### end Alembic commands ###
