"""add reseller sales tables and settings

Revision ID: 5f9663eadacb
Revises: c0318902a99a
Create Date: 2026-07-08 04:02:05.306115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9663eadacb'
down_revision: Union[str, None] = 'c0318902a99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reseller_accounts',
    sa.Column('code', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('panel_code', sa.Integer(), nullable=False),
    sa.Column('panel_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_encrypted', sa.String(length=512), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('pricing_mode', sa.String(length=20), nullable=False),
    sa.Column('data_limit', sa.BigInteger(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('purchased_volume', sa.Float(), nullable=True),
    sa.Column('createtime', sa.BigInteger(), nullable=True),
    sa.Column('expiration_time', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('billing_state', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('reseller_billing_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_code', sa.BigInteger(), nullable=False),
    sa.Column('used_traffic', sa.BigInteger(), nullable=False),
    sa.Column('billed_amount', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reseller_billing_snapshots_account_code'), 'reseller_billing_snapshots', ['account_code'], unique=False)
    op.create_table('reseller_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panel_code', sa.Integer(), nullable=False),
    sa.Column('pricing_mode', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('min_volume', sa.Float(), nullable=False),
    sa.Column('max_volume', sa.Float(), nullable=False),
    sa.Column('volume_step', sa.Float(), nullable=False),
    sa.Column('data_limit', sa.BigInteger(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=True),
    sa.Column('allowed_group_ids', sa.Text(), nullable=True),
    sa.Column('permission_overrides', sa.Text(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('display_button_text', sa.Text(), nullable=True),
    sa.Column('button_style', sa.String(length=20), nullable=True),
    sa.Column('button_icon', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('settings', sa.Column('reseller_sale_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('settings', sa.Column('reseller_usage_billing_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('settings', sa.Column('reseller_min_wallet_balance', sa.BigInteger(), server_default=sa.text('100000'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'reseller_min_wallet_balance')
    op.drop_column('settings', 'reseller_usage_billing_enabled')
    op.drop_column('settings', 'reseller_sale_mode')
    op.drop_table('reseller_plans')
    op.drop_index(op.f('ix_reseller_billing_snapshots_account_code'), table_name='reseller_billing_snapshots')
    op.drop_table('reseller_billing_snapshots')
    op.drop_table('reseller_accounts')
    # ### end Alembic commands ###
