"""move settings columns into section json fields

Revision ID: 6dbb6a2ebe16
Revises: b96b89b8f07d
Create Date: 2026-07-18 22:49:07.879028

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '6dbb6a2ebe16'
down_revision: Union[str, None] = 'b96b89b8f07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SECTION_COLUMNS = (
    'core_settings',
    'payment_settings',
    'purchase_settings',
    'service_tools_settings',
    'reseller_settings',
)

SECTION_KEYS = {
    'core_settings': (
        'bot_mode',
        'sale_mode',
        'single_panel_buy_mode',
        'channel_lock',
        'ip_mode',
        'backup_interval_hours',
    ),
    'payment_settings': (
        'pay_mode',
        'arz_mode',
        'manual_card_visibility',
        'manual_auto_confirm',
        'manual_card_random_mode',
        'manual_deposit_min',
        'manual_deposit_max',
        'crypto_deposit_min',
        'crypto_deposit_max',
        'manual_bonus_enabled',
        'manual_bonus_percent',
        'crypto_bonus_enabled',
        'crypto_bonus_percent',
        'arz_usd',
        'arz_trx',
        'arz_ton',
    ),
    'purchase_settings': (
        'extension_mode',
        'upg_mode',
        'tamdid_mode',
        'test_mode',
        'test_panel_id',
        'test_phone_verify',
    ),
    'service_tools_settings': (
        'qr_mode',
        'sub_mode',
        'other_links_mode',
        'client_list_mode',
        'usage_chart_mode',
        'change_link_mode',
        'copy_link_mode',
        'transfer_config_mode',
        'info_mode',
        'del_service_mode',
    ),
    'reseller_settings': (
        'reseller_sale_mode',
        'reseller_min_wallet_balance',
    ),
}

LEGACY_SETTINGS_COLUMNS = tuple(
    key for keys in SECTION_KEYS.values() for key in keys
)

BOOL_COLUMNS = {
    'bot_mode',
    'sale_mode',
    'single_panel_buy_mode',
    'extension_mode',
    'test_mode',
    'test_phone_verify',
    'pay_mode',
    'ip_mode',
    'arz_mode',
    'upg_mode',
    'tamdid_mode',
    'qr_mode',
    'other_links_mode',
    'sub_mode',
    'change_link_mode',
    'copy_link_mode',
    'transfer_config_mode',
    'info_mode',
    'client_list_mode',
    'usage_chart_mode',
    'del_service_mode',
    'channel_lock',
    'manual_auto_confirm',
    'manual_card_random_mode',
    'manual_bonus_enabled',
    'crypto_bonus_enabled',
    'reseller_sale_mode',
}


def _settings_columns() -> set[str]:
    return {col['name'] for col in inspect(op.get_bind()).get_columns('settings')}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    existing = _settings_columns()
    for column in SECTION_COLUMNS:
        if column not in existing:
            op.add_column('settings', sa.Column(column, sa.JSON(), nullable=True))

    existing = _settings_columns()
    legacy_present = [column for column in LEGACY_SETTINGS_COLUMNS if column in existing]
    if legacy_present:
        conn = op.get_bind()
        result = conn.execute(sa.text(
            'SELECT id, ' + ', '.join(legacy_present) + ' FROM settings'
        ))
        rows = result.mappings().all()
        update_parts = ', '.join(f'{column} = :{column}' for column in SECTION_COLUMNS)
        update_stmt = sa.text(f'UPDATE settings SET {update_parts} WHERE id = :id')
        for row in rows:
            values = {'id': row['id']}
            for section, keys in SECTION_KEYS.items():
                section_data = {}
                for key in keys:
                    if key not in legacy_present:
                        continue
                    value = row[key]
                    if key in BOOL_COLUMNS and value is not None:
                        value = bool(value)
                    section_data[key] = value
                if section == 'payment_settings':
                    section_data['pay_phone_verify'] = True
                values[section] = json.dumps(section_data, ensure_ascii=False)
            conn.execute(update_stmt, values)

    for column in SECTION_COLUMNS:
        op.execute(
            sa.text(
                f"UPDATE settings SET `{column}` = '{{}}' "
                f"WHERE `{column}` IS NULL"
            )
        )
        op.execute(
            sa.text(
                f"ALTER TABLE settings MODIFY COLUMN `{column}` JSON NOT NULL DEFAULT (JSON_OBJECT())"
            )
        )

    existing = _settings_columns()
    for column in LEGACY_SETTINGS_COLUMNS:
        if column in existing:
            op.drop_column('settings', column)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    existing = _settings_columns()
    legacy_defs = (
        ('backup_interval_hours', sa.Column('backup_interval_hours', sa.Integer(), server_default=sa.text('24'), nullable=False)),
        ('reseller_min_wallet_balance', sa.Column('reseller_min_wallet_balance', sa.BigInteger(), server_default=sa.text('100000'), nullable=False)),
        ('reseller_sale_mode', sa.Column('reseller_sale_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('crypto_bonus_percent', sa.Column('crypto_bonus_percent', sa.Integer(), server_default=sa.text('0'), nullable=False)),
        ('crypto_bonus_enabled', sa.Column('crypto_bonus_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('manual_bonus_percent', sa.Column('manual_bonus_percent', sa.Integer(), server_default=sa.text('0'), nullable=False)),
        ('manual_bonus_enabled', sa.Column('manual_bonus_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('crypto_deposit_max', sa.Column('crypto_deposit_max', sa.BigInteger(), server_default=sa.text('10000000'), nullable=False)),
        ('crypto_deposit_min', sa.Column('crypto_deposit_min', sa.BigInteger(), server_default=sa.text('50000'), nullable=False)),
        ('manual_deposit_max', sa.Column('manual_deposit_max', sa.BigInteger(), server_default=sa.text('2000000'), nullable=False)),
        ('manual_deposit_min', sa.Column('manual_deposit_min', sa.BigInteger(), server_default=sa.text('50000'), nullable=False)),
        ('manual_card_random_mode', sa.Column('manual_card_random_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('manual_auto_confirm', sa.Column('manual_auto_confirm', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('arz_ton', sa.Column('arz_ton', sa.BigInteger(), server_default=sa.text('0'), nullable=True)),
        ('arz_trx', sa.Column('arz_trx', sa.BigInteger(), server_default=sa.text('0'), nullable=True)),
        ('arz_usd', sa.Column('arz_usd', sa.BigInteger(), server_default=sa.text('0'), nullable=True)),
        ('channel_lock', sa.Column('channel_lock', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('del_service_mode', sa.Column('del_service_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('usage_chart_mode', sa.Column('usage_chart_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('client_list_mode', sa.Column('client_list_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('info_mode', sa.Column('info_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('transfer_config_mode', sa.Column('transfer_config_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('copy_link_mode', sa.Column('copy_link_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('change_link_mode', sa.Column('change_link_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('sub_mode', sa.Column('sub_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('other_links_mode', sa.Column('other_links_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('qr_mode', sa.Column('qr_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('tamdid_mode', sa.Column('tamdid_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('upg_mode', sa.Column('upg_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('arz_mode', sa.Column('arz_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('ip_mode', sa.Column('ip_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('manual_card_visibility', sa.Column('manual_card_visibility', sa.String(length=20), nullable=True)),
        ('pay_mode', sa.Column('pay_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('test_phone_verify', sa.Column('test_phone_verify', sa.Boolean(), server_default=sa.text('1'), nullable=False)),
        ('test_panel_id', sa.Column('test_panel_id', sa.BigInteger(), server_default=sa.text('0'), nullable=False)),
        ('test_mode', sa.Column('test_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('extension_mode', sa.Column('extension_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('single_panel_buy_mode', sa.Column('single_panel_buy_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('sale_mode', sa.Column('sale_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False)),
        ('bot_mode', sa.Column('bot_mode', sa.Boolean(), server_default=sa.text('1'), nullable=False)),
    )
    for name, column in legacy_defs:
        if name not in existing:
            op.add_column('settings', column)

    existing = _settings_columns()
    section_present = [column for column in SECTION_COLUMNS if column in existing]
    if section_present:
        conn = op.get_bind()
        rows = conn.execute(sa.text(
            'SELECT id, ' + ', '.join(section_present) + ' FROM settings'
        )).mappings().all()
        for row in rows:
            values = {'id': row['id']}
            assignments = []
            for section, keys in SECTION_KEYS.items():
                raw = row.get(section) if section in section_present else None
                if isinstance(raw, str):
                    try:
                        section_data = json.loads(raw)
                    except json.JSONDecodeError:
                        section_data = {}
                elif isinstance(raw, dict):
                    section_data = raw
                else:
                    section_data = {}
                for key in keys:
                    if key not in existing and key not in values:
                        continue
                    assignments.append(f'`{key}` = :{key}')
                    values[key] = section_data.get(key)
            if assignments:
                conn.execute(
                    sa.text('UPDATE settings SET ' + ', '.join(assignments) + ' WHERE id = :id'),
                    values,
                )

    existing = _settings_columns()
    for column in SECTION_COLUMNS:
        if column in existing:
            op.drop_column('settings', column)
    # ### end Alembic commands ###
