"""add hot path indexes

Revision ID: aaf40eb795d5
Revises: a1b2c3d4e5f6
Create Date: 2026-08-08 02:18:35.073074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf40eb795d5'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_panel_expiry'), 'services', ['in_panel', 'expiration_time'], unique=False)
    op.create_index(op.f('ix_services_panel_username'), 'services', ['in_panel', 'username'], unique=False)
    op.create_index(op.f('ix_tx_auto_approve_at'), 'transactions', ['auto_approve_at'], unique=False)
    op.create_index(op.f('ix_tx_status_created'), 'transactions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_tx_user_method_status'), 'transactions', ['user_id', 'method', 'status'], unique=False)
    op.create_index(op.f('ix_user_number'), 'user', ['number'], unique=False)
    op.create_index(op.f('ix_user_ref'), 'user', ['ref'], unique=False)
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    op.create_index(op.f('ix_user_time_s'), 'user', ['time_s'], unique=False)
    op.create_index(op.f('ix_crypto_status_arz'), 'cryptopayments', ['status', 'arz'], unique=False)
    op.create_index(op.f('ix_crypto_user'), 'cryptopayments', ['user_id'], unique=False)
    op.create_index(op.f('ix_reseller_tgid'), 'reseller_accounts', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_reseller_status_expiry'), 'reseller_accounts', ['status', 'expiration_time'], unique=False)
    op.create_index(op.f('ix_reseller_panel_username'), 'reseller_accounts', ['panel_code', 'username'], unique=False)
    op.create_index(op.f('ix_receipt_tx'), 'receipt_hashes', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_tx'), table_name='receipt_hashes')
    op.drop_index(op.f('ix_reseller_panel_username'), table_name='reseller_accounts')
    op.drop_index(op.f('ix_reseller_status_expiry'), table_name='reseller_accounts')
    op.drop_index(op.f('ix_reseller_tgid'), table_name='reseller_accounts')
    op.drop_index(op.f('ix_crypto_user'), table_name='cryptopayments')
    op.drop_index(op.f('ix_crypto_status_arz'), table_name='cryptopayments')
    op.drop_index(op.f('ix_user_time_s'), table_name='user')
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_index(op.f('ix_user_ref'), table_name='user')
    op.drop_index(op.f('ix_user_number'), table_name='user')
    op.drop_index(op.f('ix_tx_user_method_status'), table_name='transactions')
    op.drop_index(op.f('ix_tx_status_created'), table_name='transactions')
    op.drop_index(op.f('ix_tx_auto_approve_at'), table_name='transactions')
    op.drop_index(op.f('ix_services_panel_username'), table_name='services')
    op.drop_index(op.f('ix_services_panel_expiry'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    # ### end Alembic commands ###
