"""add referral system tables

Revision ID: b1c2d3e4f5a6
Revises: aaf40eb795d5
Create Date: 2026-08-08 18:20:00.448621

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5a6'
down_revision: str | None = 'aaf40eb795d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_rewards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_id', sa.BigInteger(), nullable=False),
    sa.Column('reward_amount', sa.BigInteger(), nullable=False),
    sa.Column('bonus_amount', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='completed', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refrewards_referrer'), 'referral_rewards', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_refrewards_referred'), 'referral_rewards', ['referred_id'], unique=False)
    op.create_table('referral_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('referral_enabled', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('referral_reward_amount', sa.BigInteger(), server_default='40000', nullable=False),
    sa.Column('referral_bonus_amount', sa.BigInteger(), server_default='40000', nullable=False),
    sa.Column('referral_banner_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_settings')
    op.drop_index(op.f('ix_refrewards_referred'), table_name='referral_rewards')
    op.drop_index(op.f('ix_refrewards_referrer'), table_name='referral_rewards')
    op.drop_table('referral_rewards')
    # ### end Alembic commands ###
