"""init

Revision ID: b85369de4f3f
Revises:
Create Date: 2026-06-25 03:44:10.920808

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b85369de4f3f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_files",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("app_key", sa.String(length=100), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=True),
        sa.Column("tag_name", sa.String(length=100), nullable=True),
        sa.Column("file_size_mb", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_app_files_app_key"), "app_files", ["app_key"], unique=False)
    op.create_table(
        "bot_texts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("lang", sa.String(length=10), nullable=True),
        sa.Column("banner_url", sa.String(length=500), nullable=True),
        sa.Column("banner_position", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "broadcast_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("target_mode", sa.String(length=30), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("delay_ms", sa.Integer(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("batch_delay_ms", sa.Integer(), nullable=False),
        sa.Column("cursor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("total_targets", sa.Integer(), nullable=False),
        sa.Column("sent_ok", sa.Integer(), nullable=False),
        sa.Column("sent_fail", sa.Integer(), nullable=False),
        sa.Column("blocked", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Integer(), nullable=False),
        sa.Column("floodwait_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.BigInteger(), nullable=True),
        sa.Column("finished_at", sa.BigInteger(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_broadcast_jobs_created_by"), "broadcast_jobs", ["created_by"], unique=False)
    op.create_index(op.f("ix_broadcast_jobs_status"), "broadcast_jobs", ["status"], unique=False)
    op.create_table(
        "channels",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("link", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_channels_id"), "channels", ["id"], unique=False)
    op.create_table(
        "cryptopayments",
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("arz", sa.String(length=20), nullable=True),
        sa.Column("amount", sa.String(length=50), nullable=False),
        sa.Column("amount_irt", sa.BigInteger(), nullable=False),
        sa.Column("paytime", sa.BigInteger(), nullable=True),
        sa.Column("createtime", sa.BigInteger(), nullable=False),
        sa.Column("msg_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_table(
        "discount_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("discount_percentage", sa.Integer(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("expiration_date", sa.BigInteger(), nullable=True),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("times_used", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "help_buttons",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("button_number", sa.Integer(), nullable=False),
        sa.Column("button_text", sa.Text(), nullable=True),
        sa.Column("button_url", sa.String(length=500), nullable=True),
        sa.Column("button_style", sa.String(length=20), nullable=True),
        sa.Column("button_icon", sa.BigInteger(), nullable=True),
        sa.Column("callback_key", sa.String(length=80), nullable=True),
        sa.Column("repo_owner", sa.String(length=120), nullable=True),
        sa.Column("repo_name", sa.String(length=120), nullable=True),
        sa.Column("categories", sa.JSON(), nullable=True),
        sa.Column("download_targets", sa.JSON(), nullable=True),
        sa.Column("default_file", sa.String(length=255), nullable=True),
        sa.Column("ios_url", sa.String(length=500), nullable=True),
        sa.Column("custom_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("button_number"),
    )
    op.create_index(op.f("ix_help_buttons_callback_key"), "help_buttons", ["callback_key"], unique=True)
    op.create_table(
        "keyboard_buttons",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("button_key", sa.String(length=100), nullable=False),
        sa.Column("button_text", sa.Text(), nullable=False),
        sa.Column("button_style", sa.String(length=20), nullable=True),
        sa.Column("button_icon", sa.BigInteger(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("button_key"),
    )
    op.create_table(
        "log_channels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("log_type", sa.String(length=50), nullable=False),
        sa.Column("destination_type", sa.String(length=20), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manual_auto_approve_rules",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("min_successful_tx", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_successful_tx", sa.Integer(), nullable=True),
        sa.Column("auto_approve_delay_minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manual_cards",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("number", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "panels",
        sa.Column("code", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("enable", sa.Boolean(), nullable=True),
        sa.Column("base_url", sa.String(length=255), nullable=False),
        sa.Column("tunnel_url", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("cookie", sa.String(length=500), nullable=False),
        sa.Column(
            "button_settings",
            sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "subscription_settings",
            sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "test_settings",
            sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "renewal_settings",
            sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "feature_settings",
            sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("storage", sa.Float(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("panel_code", sa.Integer(), nullable=False),
        sa.Column("plan_type", sa.String(length=20), nullable=False),
        sa.Column("data_limit_reset_strategy", sa.String(length=20), nullable=False),
        sa.Column("ip_limit", sa.Integer(), nullable=False),
        sa.Column("display_button_text", sa.Text(), nullable=True),
        sa.Column("button_style", sa.String(length=20), nullable=True),
        sa.Column("button_icon", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "receipt_hashes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("phash", sa.String(length=64), nullable=False),
        sa.Column("transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_receipt_hashes_phash"), "receipt_hashes", ["phash"], unique=True)
    op.create_table(
        "services",
        sa.Column("code", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("enable", sa.Boolean(), nullable=False),
        sa.Column("in_panel", sa.BigInteger(), nullable=True),
        sa.Column("panel_userid", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=True),
        sa.Column("package_size", sa.BigInteger(), nullable=True),
        sa.Column("createtime", sa.BigInteger(), nullable=True),
        sa.Column("expiration_time", sa.BigInteger(), nullable=True),
        sa.Column("warning", sa.Integer(), nullable=False),
        sa.Column("warning_time", sa.BigInteger(), nullable=True),
        sa.Column("low_volume_notified", sa.Boolean(), nullable=False),
        sa.Column("expire_notified", sa.Boolean(), nullable=False),
        sa.Column("data_limit_reset_strategy", sa.String(length=20), nullable=False),
        sa.Column("ip_limit", sa.Integer(), nullable=False),
        sa.Column("is_test", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "settings",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("bot_mode", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("sale_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("single_panel_buy_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("extension_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("test_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("test_panel_id", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("test_phone_verify", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("pay_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("ip_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("arz_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("upg_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("tamdid_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("qr_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("other_links_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("sub_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("change_link_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("copy_link_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("transfer_config_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("info_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("client_list_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("usage_chart_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("del_service_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("channel_lock", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("arz_usd", sa.BigInteger(), server_default=sa.text("0"), nullable=True),
        sa.Column("arz_trx", sa.BigInteger(), server_default=sa.text("0"), nullable=True),
        sa.Column("arz_ton", sa.BigInteger(), server_default=sa.text("0"), nullable=True),
        sa.Column("manual_auto_confirm", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("manual_card_random_mode", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("manual_deposit_min", sa.BigInteger(), server_default=sa.text("50000"), nullable=False),
        sa.Column("manual_deposit_max", sa.BigInteger(), server_default=sa.text("2000000"), nullable=False),
        sa.Column("crypto_deposit_min", sa.BigInteger(), server_default=sa.text("50000"), nullable=False),
        sa.Column("crypto_deposit_max", sa.BigInteger(), server_default=sa.text("10000000"), nullable=False),
        sa.Column("manual_bonus_enabled", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("manual_bonus_percent", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("crypto_bonus_enabled", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("crypto_bonus_percent", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("completed_at", sa.BigInteger(), nullable=True),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column("message_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("auto_approve_at", sa.BigInteger(), nullable=True),
        sa.Column("auto_approve_rule_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("time_s", sa.BigInteger(), nullable=True),
        sa.Column("ref", sa.BigInteger(), nullable=True),
        sa.Column("number", sa.String(length=20), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=True),
        sa.Column("invite", sa.Integer(), nullable=True),
        sa.Column("tested", sa.Boolean(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=5), server_default="fa", nullable=False),
        sa.Column("last_dice_roll", sa.BigInteger(), nullable=True),
        sa.Column("current_game_data", sa.String(length=100), nullable=True),
        sa.Column("show_volume", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("show_panel", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("show_service_word", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("show_config_name", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("service_buttons_per_row", sa.Integer(), server_default="1", nullable=False),
        sa.Column("service_button_rows", sa.Integer(), server_default="5", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("api_key", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallets")
    op.drop_table("user")
    op.drop_table("transactions")
    op.drop_table("settings")
    op.drop_table("services")
    op.drop_index(op.f("ix_receipt_hashes_phash"), table_name="receipt_hashes")
    op.drop_table("receipt_hashes")
    op.drop_table("plans")
    op.drop_table("panels")
    op.drop_table("manual_cards")
    op.drop_table("manual_auto_approve_rules")
    op.drop_table("log_channels")
    op.drop_table("keyboard_buttons")
    op.drop_index(op.f("ix_help_buttons_callback_key"), table_name="help_buttons")
    op.drop_table("help_buttons")
    op.drop_table("discount_codes")
    op.drop_table("cryptopayments")
    op.drop_index(op.f("ix_channels_id"), table_name="channels")
    op.drop_table("channels")
    op.drop_index(op.f("ix_broadcast_jobs_status"), table_name="broadcast_jobs")
    op.drop_index(op.f("ix_broadcast_jobs_created_by"), table_name="broadcast_jobs")
    op.drop_table("broadcast_jobs")
    op.drop_table("bot_texts")
    op.drop_index(op.f("ix_app_files_app_key"), table_name="app_files")
    op.drop_table("app_files")
    # ### end Alembic commands ###
