"""add backup_interval_hours to settings

Revision ID: b96b89b8f07d
Revises: 2cf59a786504
Create Date: 2026-07-08 13:47:52.421304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b96b89b8f07d'
down_revision: Union[str, None] = '2cf59a786504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('backup_interval_hours', sa.Integer(), server_default=sa.text('24'), nullable=False))
    op.drop_column('settings', 'reseller_usage_billing_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('reseller_usage_billing_enabled', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('settings', 'backup_interval_hours')
    # ### end Alembic commands ###
