"""add panel auth_type column

Revision ID: c0318902a99a
Revises: b85369de4f3f
Create Date: 2026-06-29 16:59:53.809822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c0318902a99a'
down_revision: Union[str, None] = 'b85369de4f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('auth_type', sa.String(length=20), nullable=False))
    op.alter_column('panels', 'password',
               existing_type=sa.String(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panels', 'password',
               existing_type=sa.String(length=512),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_column('panels', 'auth_type')
    # ### end Alembic commands ###
