"""add secrets table

Revision ID: f8c4a91e2b7d
Revises: 6dbb6a2ebe16
Create Date: 2026-08-04 14:28:53.374625

"""

from __future__ import annotations

import os
import secrets
from pathlib import Path
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8c4a91e2b7d"
down_revision: Union[str, None] = "6dbb6a2ebe16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SECRET_SEED = (
    ("crypto_key", "CRYPTO_KEY"),
    ("webhook_secret", "WEBHOOK_SECRET"),
)


def _project_root() -> Path:
    # versions/ -> migrations/ -> db/ -> app/ -> project root
    return Path(__file__).resolve().parents[4]


def _parse_dotenv(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip("'").strip('"')
        if key:
            values[key] = value
    return values


def _legacy_secret(env_key: str, dotenv: dict[str, str]) -> str:
    value = (os.environ.get(env_key) or "").strip()
    if value:
        return value
    return (dotenv.get(env_key) or "").strip()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secrets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###

    dotenv = _parse_dotenv(_project_root() / ".env")
    conn = op.get_bind()
    for name, env_key in _SECRET_SEED:
        existing = conn.execute(
            sa.text("SELECT 1 FROM secrets WHERE name = :name LIMIT 1"),
            {"name": name},
        ).scalar()
        if existing:
            continue
        value = _legacy_secret(env_key, dotenv) or secrets.token_hex(32)
        conn.execute(
            sa.text("INSERT INTO secrets (name, value) VALUES (:name, :value)"),
            {"name": name, "value": value},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("secrets")
    # ### end Alembic commands ###
