services:
  cfbot:
    build: .
    image: explosive1988/cfbot:latest
    container_name: cfbot
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - .:/app
