import asyncio
import inspect
import logging
import os
import tempfile
import time
import types
import zipfile
from contextlib import suppress as contextlib_suppress
from pathlib import Path
from typing import Any

import aiofiles

RUBIKA_ZIP_NAME = "NitoNumber-1.zip"
RUBIKA_UPLOAD_CONCURRENCY = 8
RUBIKA_UPLOAD_CHUNK = 1024 * 1024

logging.getLogger("rubpy").setLevel(logging.INFO)
logging.getLogger("rubpy.network").setLevel(logging.INFO)

from rubpy import Client
from rubpy import exceptions as rubpy_exceptions
from rubpy.exceptions import RPCError
from rubpy.types import Update

from App.config import Settings

logger = logging.getLogger(__name__)


class RubikaError(Exception):
    pass


class RubikaUploader:
    """Send files to Rubika users by their @username using the bot-owned account.

    Auth is via a pre-existing rubpy session file (`.rp`) generated by
    `session_rubika.py`. If the session file is missing, the uploader is
    disabled and no Telegram side-effects fire.
    """

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._client: Client | None = None
        self._lock = asyncio.Lock()
        self._connect_lock = asyncio.Lock()
        self._ready = False

    @property
    def session_path(self) -> Path:
        return self._settings.rubika_session_dir / f"{self._settings.rubika_session_name}.rp"

    @property
    def enabled(self) -> bool:
        return self.session_path.exists()

    async def connect(self) -> None:
        if self._ready and self._client is not None:
            return
        async with self._connect_lock:
            if self._ready and self._client is not None:
                return
            if not self.enabled:
                logger.info(
                    "[rubika] session file %s not present; uploader disabled. "
                    "Run `python session_rubika.py` to create it.",
                    self.session_path,
                )
                return
            self._settings.rubika_session_dir.mkdir(parents=True, exist_ok=True)
            session_name = str(
                self._settings.rubika_session_dir / self._settings.rubika_session_name
            )
            logger.info("[rubika] starting client (session=%s)", session_name)
            client = Client(session_name)
            try:
                await client.start()
                _install_parallel_uploader(client)
                me = await client.get_me()
            except rubpy_exceptions.NotRegistered as exc:
                with contextlib_suppress(Exception):
                    await client.disconnect()
                raise RubikaError(
                    "Rubika session is invalid or revoked. "
                    "Re-run `python session_rubika.py` to re-authenticate."
                ) from exc
            except RPCError as exc:
                with contextlib_suppress(Exception):
                    await client.disconnect()
                raise RubikaError(f"rubika connect failed: {exc}") from exc
            self._client = client
            self._ready = True
            logger.info(
                "[rubika] logged in as %s (guid=%s)",
                getattr(me.user, "username", None) or getattr(me.user, "first_name", "?"),
                me.user.user_guid,
            )

    async def close(self) -> None:
        if self._client is None:
            return
        try:
            await self._client.disconnect()
        except Exception as exc:  # noqa: BLE001
            logger.warning("[rubika] disconnect error: %s", exc)
        self._client = None
        self._ready = False

    async def resolve_username(self, username: str) -> dict[str, Any]:
        """Look up a Rubika user by @username. Returns dict with object_guid, type, name."""
        await self.connect()
        if self._client is None:
            raise RubikaError("Rubika is not configured (session missing).")
        username = username.strip().lstrip("@")
        if not username:
            raise RubikaError("نام کاربری روبیکا خالی است.")
        try:
            result = await self._client.get_object_by_username(username)
        except RPCError as exc:
            raise RubikaError(f"lookup failed: {exc}") from exc

        user = getattr(result, "user", None)
        channel = getattr(result, "channel", None)
        target = user or channel
        if target is None:
            raise RubikaError("کاربر روبیکا پیدا نشد.")

        guid = getattr(target, "user_guid", None) or getattr(target, "channel_guid", None) \
            or getattr(target, "object_guid", None)
        if not guid:
            raise RubikaError("شناسه کاربر روبیکا پیدا نشد.")
        return {
            "object_guid": guid,
            "type": "User" if user is not None else "Channel",
            "name": getattr(target, "first_name", "") or getattr(target, "title", "") or username,
        }

    async def send_file(
        self,
        file_path: Path,
        target_username: str,
        caption: str | None = None,
    ) -> dict[str, Any]:
        """Resolve username, upload the file, and post it to the target's DM."""
        if not file_path.exists():
            raise RubikaError(f"فایل پیدا نشد: {file_path}")

        async with self._lock:
            await self.connect()
            if self._client is None:
                raise RubikaError("Rubika uploader غیرفعال است.")

            target = await self.resolve_username(target_username)
            logger.info(
                "[rubika] sending %s (%d bytes) to %s (%s)",
                file_path.name, file_path.stat().st_size, target["name"], target["object_guid"],
            )

            with tempfile.TemporaryDirectory(prefix="rb_zip_") as tmp_dir:
                zip_path = Path(tmp_dir) / RUBIKA_ZIP_NAME
                await asyncio.to_thread(_zip_file, file_path, zip_path)
                zip_size = zip_path.stat().st_size
                logger.info(
                    "[rubika] zipped to %s (%d bytes)", zip_path.name, zip_size,
                )
                last_logged_pct = -1
                start_ts = time.monotonic()
                last_chunk_ts = start_ts

                def _progress(total: int, uploaded: int) -> None:
                    nonlocal last_logged_pct, last_chunk_ts
                    now = time.monotonic()
                    elapsed = now - start_ts
                    since_last = now - last_chunk_ts
                    last_chunk_ts = now
                    pct = int(uploaded * 100 / total) if total else 100
                    rate = (uploaded / elapsed / 1024) if elapsed > 0 else 0
                    if pct >= last_logged_pct + 5 or uploaded >= total:
                        last_logged_pct = pct
                        logger.info(
                            "[rubika] upload %d%% (%d/%d bytes, %.1f KB/s, +%.1fs)",
                            pct, uploaded, total, rate, since_last,
                        )

                logger.info(
                    "[rubika] send_message start (timeout=%ds, size=%d B)",
                    self._settings.rubika_upload_timeout, zip_size,
                )
                try:
                    update = await asyncio.wait_for(
                        self._client.send_message(
                            object_guid=target["object_guid"],
                            text=caption or None,
                            file_inline=str(zip_path),
                            type="File",
                            file_name=RUBIKA_ZIP_NAME,
                            callback=_progress,
                        ),
                        timeout=self._settings.rubika_upload_timeout,
                    )
                except asyncio.TimeoutError as exc:
                    elapsed = time.monotonic() - start_ts
                    logger.error(
                        "[rubika] TIMEOUT after %.1fs, last_pct=%d, idle_for=%.1fs",
                        elapsed, last_logged_pct, time.monotonic() - last_chunk_ts,
                    )
                    raise RubikaError(
                        f"upload timed out at {last_logged_pct}% after {elapsed:.0f}s"
                    ) from exc
                except RPCError as exc:
                    logger.exception("[rubika] RPCError during send_message")
                    raise RubikaError(f"send failed: {exc}") from exc
                except Exception as exc:
                    logger.exception("[rubika] unexpected error during send_message")
                    raise RubikaError(f"send failed: {exc!r}") from exc

            message_id = getattr(update, "message_id", None) or getattr(update, "id", None)
            logger.info("[rubika] delivered, message_id=%s", message_id)
            return {
                "object_guid": target["object_guid"],
                "name": target["name"],
                "message_id": message_id,
            }


def _zip_file(src: Path, dst: Path) -> None:
    with zipfile.ZipFile(dst, "w", compression=zipfile.ZIP_STORED) as zf:
        zf.write(src, arcname=src.name)


async def _parallel_upload_file(
    self,
    file,
    mime=None,
    file_name=None,
    chunk: int = RUBIKA_UPLOAD_CHUNK,
    callback=None,
    max_retries: int = 3,
    backoff: float = 1.0,
    concurrency: int = RUBIKA_UPLOAD_CONCURRENCY,
    *args,
    **kwargs,
):
    """Parallel-chunk replacement for rubpy.network.Connection.upload_file.

    Same init handshake (request_send_file), same per-chunk POST headers and
    retry policy. Difference: chunks upload concurrently via asyncio.gather
    with a bounded semaphore. On ERROR_TRY_AGAIN the entire upload restarts
    (matches stock rubpy behavior).
    """
    if isinstance(file, str):
        if not os.path.exists(file):
            raise ValueError("File not found at the given path.")
        file_name = file_name or os.path.basename(file)
        file_size = os.path.getsize(file)
        is_path = True
    elif isinstance(file, bytes):
        if not file_name:
            raise ValueError("file_name must be specified when uploading from bytes.")
        file_size = len(file)
        is_path = False
    else:
        raise TypeError("file must be a file path (str) or raw bytes.")

    mime = mime or file_name.split(".")[-1]

    async def handle_callback(total: int, current: int) -> None:
        if not callable(callback):
            return
        try:
            if inspect.iscoroutinefunction(callback):
                await callback(total, current)
            else:
                callback(total, current)
        except Exception as e:  # noqa: BLE001
            self.logger.error(f"Callback error: {e}")

    while True:
        init = await self.client.request_send_file(file_name, file_size, mime)
        file_id = init.id
        dc_id = init.dc_id
        upload_url = init.upload_url
        access_hash_send = init.access_hash_send
        total_parts = (file_size + chunk - 1) // chunk

        sem = asyncio.Semaphore(concurrency)
        progress_lock = asyncio.Lock()
        uploaded = 0
        reinit = asyncio.Event()
        final_chunk_resp: dict = {}

        async def upload_chunk(part_number: int):
            nonlocal uploaded
            if reinit.is_set():
                return
            offset = (part_number - 1) * chunk
            size = min(chunk, file_size - offset)
            if is_path:
                async with aiofiles.open(file, "rb") as f:
                    await f.seek(offset)
                    data = await f.read(size)
            else:
                data = file[offset : offset + size]

            async with sem:
                if reinit.is_set():
                    return
                for attempt in range(max_retries):
                    try:
                        async with self.session.post(
                            url=upload_url,
                            headers={
                                "auth": self.client.auth,
                                "file-id": file_id,
                                "total-part": str(total_parts),
                                "part-number": str(part_number),
                                "chunk-size": str(len(data)),
                                "access-hash-send": access_hash_send,
                            },
                            data=data,
                            proxy=self.client.proxy,
                        ) as response:
                            resp = await response.json()
                        if resp.get("status") == "ERROR_TRY_AGAIN":
                            reinit.set()
                            return
                        async with progress_lock:
                            uploaded += len(data)
                            cur = uploaded
                        await handle_callback(file_size, cur)
                        if part_number == total_parts:
                            final_chunk_resp["resp"] = resp
                        return resp
                    except Exception as e:  # noqa: BLE001
                        self.logger.warning(
                            f"Error uploading chunk {part_number} "
                            f"(attempt {attempt + 1}/{max_retries}): {e}"
                        )
                        if attempt < max_retries - 1:
                            await asyncio.sleep(backoff * (2 ** attempt))
                        else:
                            raise

        tasks = [
            asyncio.create_task(upload_chunk(n)) for n in range(1, total_parts + 1)
        ]
        try:
            await asyncio.gather(*tasks)
        except Exception:
            for t in tasks:
                if not t.done():
                    t.cancel()
            raise

        if reinit.is_set():
            self.logger.warning("Server requested reinitialization. Restarting upload.")
            continue

        upload_result = final_chunk_resp.get("resp") or {}
        if (
            upload_result.get("status") == "OK"
            and upload_result.get("status_det") == "OK"
        ):
            return Update(
                {
                    "mime": mime,
                    "size": file_size,
                    "dc_id": dc_id,
                    "file_id": file_id,
                    "file_name": file_name,
                    "access_hash_rec": upload_result["data"]["access_hash_rec"],
                }
            )
        raise rubpy_exceptions(upload_result.get("status_det"))(upload_result)


def _install_parallel_uploader(client: Client) -> None:
    conn = getattr(client, "connection", None)
    if conn is None:
        logger.warning("[rubika] no connection on client, skip parallel patch")
        return
    conn.upload_file = types.MethodType(_parallel_upload_file, conn)
    logger.info(
        "[rubika] parallel uploader installed (concurrency=%d, chunk=%d B)",
        RUBIKA_UPLOAD_CONCURRENCY, RUBIKA_UPLOAD_CHUNK,
    )
